MyEmoji/blog/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', photo, name="photo"),
    path('create/', photoCreate, name="photo_create"),
    path('detail/<int:pk>/', photoDetail, name="photo_detail"),
    path('delete/<int:pk>/', photoDelete, name="photo_delete"),
    path('edit/<int:pk>/', photoEdit, name="photo_edit"),
    path('search/', photolsearchResult, name="photo_search"),
]

MyEmoji/chat/urls.py
# chat/urls.py

from django.urls import path
# from .views import *

# urlpatterns = [
#     path('', chat, name='chat'),
#     path('<str:room_name>/', room, name='room')
# ]

from chat import views
# URL Reverse시의 namespace로서 활용
app_name = "chat"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_pk>/chat/", views.room_chat, name="room_chat"),
    path("new/", views.room_new, name="room_new"),
]

MyEmoji/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),

    path('accounts/', include('accounts.urls')),
    path('emo_create/', include('emo_create.urls')),
    path('blog/', include('blog.urls')),
    # 아래꺼 지워야함
    path('', RedirectView.as_view(pattern_name="chat:index"), name="root"),
    path('emo_create/', include('emo_create.urls')),
    path('emo_board/', include('blog.urls')),
    path('chat/', include('chat.urls')),
    path('my_emoticon/', include('my_emoticon.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyEmoji/chat/models.py
from django.db import models

# Create your models here.
class Room(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ["-pk"]

MyEmoji/chat/forms.py
# chat/forms.py

from django import forms
from chat.models import Room


class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ["name"]

MyEmoji/chat/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest, HttpResponse
from chat.models import Room
from chat.forms import RoomForm
from django.contrib.auth.decorators import login_required

# Create your views here.


# def chat(request):
#     return render(request, 'chat.html')


# def room(request, room_name):
#     return render(request, 'room.html', {
#         'room_name': room_name
#     })

def index(request: HttpRequest) -> HttpResponse:

    room_qs = Room.objects.all()
    return render(request, 'chat/index.html', {
        "room_list": room_qs,
    })
# if request.user.is_authenticated:
# else:
#     return render(request, 'login.html')


@login_required
def room_chat(requset: HttpRequest, room_pk: int) -> HttpResponse:
    room = get_object_or_404(Room, pk=room_pk)
    return render(requset, 'chat/room_chat.html', {
        "room_name": room,
    })


@login_required
def room_new(request):
    if request.method == 'POST':
        form = RoomForm(request.POST)
        if form.is_valid():
            created_room: Room = form.save()
            return redirect("chat:room_chat", created_room.pk)
    else:
        form = RoomForm()

    return render(request, 'chat/room_form.html', {
        "form": form,
    })

MyEmoji/chat/templates/chat/base.html
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <title>Django Channels</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% block extra-style %}{% endblock %}
</head>

<body>
    {% bootstrap_messages %}
    {% block content %}{% endblock %}
    {% block extra-script %}{% endblock %}
</body>

</html>

MyEmoji/chat/templates/chat/index.html
{% extends 'chat/base.html' %}

{% block title %}
Chat(Index)
{% endblock %}

{% block content %}
<div class="chat_wrap">
    <h1>채팅방 목록</h1>

    <ul>
        {% for room in room_list%}
        <li>
            <a href="{% url 'chat:room_chat' room.pk %} ">{{ room.name }}</a>
        </li>
        {% endfor %}
    </ul>
    <hr />
    <a href="{% url 'chat:room_new' %}">새 채팅방 만들기</a>
</div>
{% endblock %}

MyEmoji/chat/templates/chat/room_chat.html
{% extends 'chat/base.html' %}

{% block title %}
Chat(room_chat)
{% endblock %}

{% block extra-style %}
<style>
    .chat-message>div {
        background-color: #3b3b3b;
        color: #e1e1e1;
        border-radius: 0.8em;
        padding: 0.4em;
        margin: 0.4em 0;
        display: inline-block;
        white-space: pre-wrap;
        max-width: 80%;
        word-wrap: break-word;
    }

    .chat-message.me {
        text-align: right;
    }

    .chat-message.me>div {
        background-color: #1f8cff;
        color: #fff;
        text-align: left;
    }
</style>
{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row">
        <div class="col-sm-12">
            <div class="card" style="height: 600px;">
                <div class="card-header">
                    채팅방: {{ room_name }}
                </div>
                <div class="card-body overflow-hidden">
                    <div id="chat_messages" class="w-100 h-100 border-0 overflow-scroll"></div>
                </div>
                <div class="card-footer">
                    <form action="#" id="message_form">

                        <input type="text" name="message" class="form-control" autofocus autocomplete="off">
                    </form>
                </div>
            </div>

            <hr class="my-3">

            <a href="{% url 'chat:index' %}" class="btn btn-primary">대기실로 이동</a>
        </div>
    </div>
</div>
{% endblock %}

{% block extra-script %}
<script>
    const handlers = {
        chat_messages_tag: null,
        ws: null,
        retry: 0,

        init() {
            this.chat_messages_tag = document.querySelector("#chat_messages");
            document.querySelector("#message_form")
                .addEventListener("submit", this.onsubmit.bind(this));
        },
        connect(ws_url) {
            if (this.ws) this.ws.close();

            this.ws = new WebSocket(ws_url || this.ws?.url);

            this.ws.onopen = this.onopen.bind(this);
            this.ws.onclose = this.onclose.bind(this);
            this.ws.onerror = this.onerror.bind(this);
            this.ws.onmessage = this.onmessage.bind(this);
        },
        reconnect() {
            this.connect();
        },
        onopen() {
            console.log("웹소켓 서버와 접속");
            this.retry = 0;
        },
        onclose(event) {
            if (!event.wasClean) {
                console.error("웹소켓 서버가 죽었거나, 네트워크 장애입니다.");
                if (this.retry < 3) {
                    this.retry += 1;
                    setTimeout(() => {
                        this.reconnect();
                        console.log(`[${this.retry}] 접속 재시도 ...`);
                    }, 1000 * this.retry)
                }
                else {
                    console.log("웹소켓 서버에 접속할 수 없습니다. 대기실로 이동합니다.");
                    window.location.href = "{% url 'chat:index' %}";
                }
            }
        },
        onerror() {
            console.log("웹소켓 에러가 발생했습니다. 대기실로 이동합니다.");
            window.location.href = "{% url 'chat:index' %}";
        },
        onmessage(event) {
            const message_json = event.data;
            console.log("메세지 수신 :", message_json);

            const { type, message, sender } = JSON.parse(message_json);
            switch (type) {
                case "chat.message":
                    this.append_message(message, sender);
                    break;

                default:
                    console.error(`Invalid message type : ${type}`);
            }
        },
        append_message(message, sender) {
            // console.log(typeof message);
            const element = document.createElement("div");
            element.className = "chat-message";

            let user_id = "";
            if (sender === "{{ user.username }}") {
                element.className += " me";
            } else if (sender) {
                user_id = `id : ${sender}\n`;
            }

            const wrapper = document.createElement("div");
            wrapper.textContent = user_id + message;
            element.appendChild(wrapper);

            this.chat_messages_tag.appendChild(element);
            this.chat_messages_tag.scrollTop = this.chat_messages_tag.scrollHeight;

        },
        onsubmit(event) {
            event.preventDefault();

            const form_data = new FormData(event.target);
            const props = Object.fromEntries(form_data);
            event.target.reset();  // reset form

            const { message } = props;
            console.log("웹소켓으로 전송할 메세지 :", message);

            // this.append_message(message);

            this.ws.send(JSON.stringify({
                type: "chat.message",
                message: message,
            }))
        },
    };

    handlers.init();

    const protocol = location.protocol === "http:" ? "ws:" : "wss:";
    const ws_url = protocol + "//" + location.host + "/ws" + location.pathname;
    handlers.connect(ws_url);
</script>
{% endblock %}

MyEmoji/chat/templates/chat/room_form.html
{% load django_bootstrap5%}

<h2>새 채팅방 만들기</h2>

<div class="my-3">
    <form action="" method="post">
        {% csrf_token %}

        {% bootstrap_form form %}
        <input type="submit" value="만들기" class="btn btn-primary" />
    </form>
</div>

<a href="{% url 'chat:index' %}" class="btn btn-primary">
    대기실로 이동
</a>